In [49]:
import sklearn
from logging import warning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings

warnings.filterwarnings('ignore')

%matplotlib inline

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import AdaBoostRegressor,RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.model_selection import RandomizedSearchCV

from xgboost import XGBRegressor

In [50]:
!pip install catboost

Requirement already satisfied: catboost in c:\users\ajinkya\anaconda3\lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in c:\users\ajinkya\anaconda3\lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\users\ajinkya\anaconda3\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\ajinkya\anaconda3\lib\site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\ajinkya\anaconda3\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\ajinkya\anaconda3\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in c:\users\ajinkya\anaconda3\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in c:\users\ajinkya\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ajinkya\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ajinkya\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ajinkya\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ajinkya\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\ajinkya\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ajinkya\anaconda3\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ajinkya\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\ajinkya\anaconda3\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\ajinkya\anaconda3\lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ajinkya\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\ajinkya\anaconda3\lib\site-packages (from plotly->catboost) (2.7.0)

In [51]:
df=pd.read_csv('data/StudentsPerformance.csv')

In [52]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [53]:
X=df.drop(columns=['math score'],axis=1)

In [54]:
y=df['math score']

In [55]:
## Create column transformer

num_features=X.select_dtypes(exclude="object").columns
cat_features=X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer=StandardScaler()
oh_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OnehotEncoder",oh_transformer,cat_features),
        ("StandardScaler",numeric_transformer,num_features)
    ]
)

In [56]:
X=preprocessor.fit_transform(X)

In [67]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((800, 19), (200, 19))

In [68]:
from math import sqrt
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2score=r2_score(true,predicted)
    return mae,rmse,r2score

In [69]:
models={
    "Linear Regression":LinearRegression(),
    "Ridge Regression":Ridge(),
    "Lasso Regression":Lasso(),
    "KNN Regression":KNeighborsRegressor(),
    "DT Regression":DecisionTreeRegressor(),
    "Random Forest Regression":RandomForestRegressor(),
    "XGB Regression":XGBRegressor(),
    "Adaboost Regression":AdaBoostRegressor()
}

In [70]:
print(model_train_r2)
print(type(model_train_r2))

(4.266711846071957, np.float64(5.323050852720514), 0.8743172040139593)
<class 'tuple'>

In [75]:
model_list=[]
r2_list=[]


for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)

   
    model_train_rmse, model_train_mae, model_train_r2score = evaluate_model(
        y_train,
        y_train_pred
    )
   
    model_test_rmse, model_test_mae, model_test_r2score = evaluate_model(
        y_test,
        y_test_pred
    )

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    r2_list.append(model_test_r2score)

    print("Model performance for Training set")

    print("Model performance for Training set")
    print("- RMSE: {:.4f}".format(model_train_rmse))
    print("- MAE: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2score))



    print("---------------------------------------------------------")
    
    print("Model performance for Testing set")
    print("- RMSE: {:.4f}".format(model_test_rmse))
    print("- MAE: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2score))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
Model performance for Training set
- RMSE: 4.2667
- MAE: 5.3231
- R2 Score: 0.8743
---------------------------------------------------------
Model performance for Testing set
- RMSE: 4.2148
- MAE: 5.3940
- R2 Score: 0.8804
===================================


Ridge Regression
Model performance for Training set
Model performance for Training set
- RMSE: 4.2650
- MAE: 5.3233
- R2 Score: 0.8743
---------------------------------------------------------
Model performance for Testing set
- RMSE: 4.2111
- MAE: 5.3904
- R2 Score: 0.8806
===================================


Lasso Regression
Model performance for Training set
Model performance for Training set
- RMSE: 5.2063
- MAE: 6.5938
- R2 Score: 0.8071
---------------------------------------------------------
Model performance for Testing set
- RMSE: 5.1579
- MAE: 6.5197
- R2 Score: 0.8253
===================================


KNN Regression
Model performance for Training set
Model performance for Training set
- RMSE: 4.5177
- MAE: 5.7088
- R2 Score: 0.8554
---------------------------------------------------------
Model performance for Testing set
- RMSE: 5.6090
- MAE: 7.2494
- R2 Score: 0.7840
===================================


DT Regression
Model performance for Training set
Model performance for Training set
- RMSE: 0.0187
- MAE: 0.2795
- R2 Score: 0.9997
---------------------------------------------------------
Model performance for Testing set
- RMSE: 6.4750
- MAE: 8.1808
- R2 Score: 0.7250
===================================


Random Forest Regression
Model performance for Training set
Model performance for Training set
- RMSE: 1.8488
- MAE: 2.3152
- R2 Score: 0.9762
---------------------------------------------------------
Model performance for Testing set
- RMSE: 4.7449
- MAE: 6.0700
- R2 Score: 0.8486
===================================


XGB Regression
Model performance for Training set
Model performance for Training set
- RMSE: 0.6875
- MAE: 1.0073
- R2 Score: 0.9955
---------------------------------------------------------
Model performance for Testing set
- RMSE: 5.0577
- MAE: 6.4733
- R2 Score: 0.8278
===================================


Adaboost Regression
Model performance for Training set
Model performance for Training set
- RMSE: 4.7840
- MAE: 5.8879
- R2 Score: 0.8462
---------------------------------------------------------
Model performance for Testing set
- RMSE: 4.8119
- MAE: 6.1742
- R2 Score: 0.8433
===================================

In [76]:
## Best r2

pd.DataFrame(list(zip(model_list,r2_list)),columns=['Model Name','R2_Score']).sort_values(by=['R2_Score'],ascending=False)

                 Model Name  R2_Score
1          Ridge Regression  0.880593
0         Linear Regression  0.880433
5  Random Forest Regression  0.848588
7       Adaboost Regression  0.843345
6            XGB Regression  0.827797
2          Lasso Regression  0.825320
3            KNN Regression  0.784030
4             DT Regression  0.724971